### ISSUE TITLE
Specify in which Queue a completion block should be executed

### ISSUE THREAD

**Issue by isaacroldan** [carambalabs/CarambaKit#21]
## What

Right now we are executing completion blocks in a background thread, this could be a potential problem for future uses (like `UnsplashKit`)

## Proposal
When executing a request, specify in which Queue the completion block should be called. If not specified, the Main queue should be used by default.

**Comment by pepicrft** [comment]
Fixed here https://github.com/carambalabs/CarambaKit/commit/dc693353774bf20ba5a6d3c2c3e02929a1c6f51d
