### ISSUE TITLE
CarambaKit should return both Data and URLResponse in each request

### ISSUE THREAD

**Issue by isaacroldan** [carambalabs/CarambaKit#22]
## What

Right now someone using CarambaKit can pass an adapter from Data to a custom Object when doing a network request. But sometimes you need to look at the URLResponse too see the headers info.

CarambaKit should expose both Data and URLResponse to users.

**Comment by pepicrft** [comment]
Solved here https://github.com/carambalabs/CarambaKit/commits/master
